GET http://localhost:5012/students

###
GET http://localhost:5012/students/1


###
POST http://localhost:5012/students
Content-Type: application/json

{
    "name": "Preetpal Singh",
    "fatherName": "Jasmeet Singh",
    "motherName": "Sunita Kaur",
    "email": "akashnew@gmail.com",
    "address": {
        "addressLine1": "Address line 1",
        "city": "Vikaspuri",
        "state": "Delhi",
        "pincode": 110018
    },
    "familyMembers": [
        {
            "name": "Jasmeet Singh",
            "relationship": "Father"
        },
        {
            "name": "Sunita Kaur",
            "relationship": "Mother"
        },
        {
            "name": "Rashmita kaur",
            "relationship": "Sister"
        }
    ],
    "certifications": [
        {
            "name": "Full Stack Development",
            "institution": "Udemy"
        },
        {
            "name": "Devops Engineer Course",
            "institution": "Udemy"
        }
    ]
}


###

DELETE http://localhost:5012/students/1


